name: tremo_prompt
description: TremoPrompt - Advanced AI prompt organizer and manager
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database & Storage
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  icons_plus: ^5.0.0
  google_fonts: ^6.1.0
  
  # Text Editor & Code Highlighting
  flutter_code_editor: ^0.3.0
  
  # File Operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.1
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # Drag & Drop
  reorderables: ^0.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

msix:
  display_name: TremoPrompt
  publisher_display_name: Tremowaves
  identity_name: Tremowaves.TremoPrompt
  msix_version: 1.0.2.0
  description: TremoPrompt - Advanced AI prompt organizer and manager
  execution_alias: tremoprompt
  logo_path: assets/icons/app_icon.png 

# MSIX Configuration for Windows Store
msix_config:
  display_name: TremoPrompt
  publisher_display_name: Tremowaves
  identity_name: Tremowaves.TremoPrompt
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  start_menu_icon_path: windows/runner/resources/app_icon.ico
  tile_icon_path: windows/runner/resources/app_icon.ico
  icons_background_color: '#1976D2'
  architecture: x64
  capabilities: 'internetClient,privateNetworkClientServer,documentsLibrary'
  languages: en-us,vi-vn
  store: false
  sign_msix: false
  install_certificate: false 