name: prompt_manager
description: "A professional application to manage, create, and use AI prompts efficiently."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management (as per document)
  provider: ^6.1.1

  # UI & Components (as per document)
  cupertino_icons: ^1.0.2
  flutter_code_editor: ^0.3.0 # For template editing
  icons_plus: ^5.0.0 # For rich icon library

  # Utilities
  google_fonts: ^6.1.0 # For Inter/Roboto/Fira Code fonts
  path_provider: ^2.1.2 # To find local paths for database
  sqflite: ^2.3.2 # For local database
  path: ^1.8.3
  flutter_highlight: ^0.7.0 # Syntax highlighting for code editor
  highlight: ^0.7.0 
  uuid: ^4.3.3
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 